# Generated by Django 3.2.9 on 2021-11-07 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('species', models.CharField(choices=[('Abuta', 'Abuta'), ('Acacia', 'Acacia'), ('Acalypha', 'Acalypha'), ('Acer', 'Acer'), ('Adenanthos', 'Adenanthos'), ('Aerangis', 'Aerangis'), ('Agave', 'Agave'), ('Aiphanes', 'Aiphanes'), ('Albizia', 'Albizia'), ('Allium', 'Allium'), ('Aloe', 'Aloe'), ('Amaranthus', 'Amaranthus'), ('Amomum', 'Amomum'), ('Angraecum', 'Angraecum'), ('Annona', 'Annona'), ('Anthurium', 'Anthurium'), ('Antirrhinum', 'Antirrhinum'), ('Arabis', 'Arabis'), ('Arceuthobium', 'Arceuthobium'), ('Ardisia', 'Ardisia'), ('Aristida', 'Aristida'), ('Asparagus', 'Asparagus'), ('Astragalus', 'Astragalus'), ('Attalea', 'Attalea'), ('Baccharis', 'Baccharis'), ('Baeckea', 'Baeckea'), ('bamboo', 'bamboo'), ('Banksia', 'Banksia'), ('Banksia ser. Dryandra', 'Banksia ser. Dryandra'), ('Begonia', 'Begonia'), ('Berberis and Mahonia', 'Berberis and Mahonia'), ('Betula', 'Betula'), ('transferred Blechnum', 'transferred Blechnum'), ('species used in bonsai', 'species used in bonsai'), ('Boronia', 'Boronia'), ('Brachyscome', 'Brachyscome'), ('Bryum', 'Bryum'), ('Bulbophyllum', 'Bulbophyllum'), ('Caladenia', 'Caladenia'), ('Campanula', 'Campanula'), ('Canna', 'Canna'), ('Cardamine', 'Cardamine'), ('Carex', 'Carex'), ('Castanopsis', 'Castanopsis'), ('Centaurea', 'Centaurea'), ('Chamelaucium', 'Chamelaucium'), ('Coccothrinax', 'Coccothrinax'), ('Coleus', 'Coleus'), ('Commelina', 'Commelina'), ('Convolvulus', 'Convolvulus'), ('Cordia', 'Cordia'), ('Corymbia', 'Corymbia'), ('Cousinia', 'Cousinia'), ('Crepidium', 'Crepidium'), ('Crinum', 'Crinum'), ('Crotalaria', 'Crotalaria'), ('Croton', 'Croton'), ('Cryptocarya', 'Cryptocarya'), ('Cuscuta', 'Cuscuta'), ('cycad by country', 'cycad by country'), ('Cyperus', 'Cyperus'), ('Dahlia', 'Dahlia'), ('Delphinium', 'Delphinium'), ('Dendrobium', 'Dendrobium'), ('Dendrochilum', 'Dendrochilum'), ('Desmodium', 'Desmodium'), ('Diospyros', 'Diospyros'), ('Taxonomy of Drosera', 'Taxonomy of Drosera'), ('Drosera', 'Drosera'), ('Durio', 'Durio'), ('Elaeocarpus', 'Elaeocarpus'), ('Elaphoglossum', 'Elaphoglossum'), ('elm', 'elm'), ('Encyclia', 'Encyclia'), ('Epidendrum', 'Epidendrum'), ('Eragrostis', 'Eragrostis'), ('Eremophila', 'Eremophila'), ('Erica', 'Erica'), ('Erigeron', 'Erigeron'), ('Erysimum', 'Erysimum'), ('Eucalyptus', 'Eucalyptus'), ('Eugenia', 'Eugenia'), ('Eulophia', 'Eulophia'), ('Euphorbia', 'Euphorbia'), ('Ficus', 'Ficus'), ('Fritillaria', 'Fritillaria'), ('Galium', 'Galium'), ('Garcinia', 'Garcinia'), ('Geranium', 'Geranium'), ('Geum', 'Geum'), ('Goodenia', 'Goodenia'), ('Grevillea', 'Grevillea'), ('Grewia', 'Grewia'), ('Guzmania', 'Guzmania'), ('Habenaria', 'Habenaria'), ('hawthorn with yellow fruit', 'hawthorn with yellow fruit'), ('Helichrysum', 'Helichrysum'), ('Hibbertia', 'Hibbertia'), ('Hieracium', 'Hieracium'), ('Hippeastrum', 'Hippeastrum'), ('Hoya', 'Hoya'), ('Hypericum', 'Hypericum'), ('Hypericum sect. Adenosepalum', 'Hypericum sect. Adenosepalum'), ('Ilex', 'Ilex'), ('Impatiens', 'Impatiens'), ('Inga', 'Inga'), ('Ipomoea', 'Ipomoea'), ('Iris', 'Iris'), ('Isolepis', 'Isolepis'), ('Ixora', 'Ixora'), ('Jasminum', 'Jasminum'), ('Justicia', 'Justicia'), ('Lepanthes', 'Lepanthes'), ('Licania', 'Licania'), ('Lilium', 'Lilium'), ('Lithocarpus', 'Lithocarpus'), ('Lobelia', 'Lobelia'), ('Lonchocarpus', 'Lonchocarpus'), ('Masdevallia', 'Masdevallia'), ('Maxillaria', 'Maxillaria'), ('Melaleuca', 'Melaleuca'), ('Miconia', 'Miconia'), ('Millettia', 'Millettia'), ('Myristica', 'Myristica'), ('Narcissus', 'Narcissus'), ('Nepenthes', 'Nepenthes'), ('Nepenthes by distribution', 'Nepenthes by distribution'), ('Nicotiana', 'Nicotiana'), ('Oberonia', 'Oberonia'), ('Ocotea', 'Ocotea'), ('Oenothera', 'Oenothera'), ('Omphalodes', 'Omphalodes'), ('Ornithogalum', 'Ornithogalum'), ('Oxalis', 'Oxalis'), ('Pabstiella', 'Pabstiella'), ('Taxonomy of Pachypodium', 'Taxonomy of Pachypodium'), ('Pandanus', 'Pandanus'), ('Panicum', 'Panicum'), ('Passiflora', 'Passiflora'), ('Pavonia', 'Pavonia'), ('Pelargonium', 'Pelargonium'), ('Peperomia', 'Peperomia'), ('Persea', 'Persea'), ('Phacelia', 'Phacelia'), ('Philodendron', 'Philodendron'), ('Phyllanthus', 'Phyllanthus'), ('Pilea', 'Pilea'), ('Pinguicula', 'Pinguicula'), ('Pinus', 'Pinus'), ('Piper', 'Piper'), ('Planchonella', 'Planchonella'), ('Pleurothallis', 'Pleurothallis'), ('Polygala', 'Polygala'), ('Potentilla', 'Potentilla'), ('Prasophyllum', 'Prasophyllum'), ('Primula', 'Primula'), ('Protea', 'Protea'), ('Prunus', 'Prunus'), ('Psychotria', 'Psychotria'), ('Ptilotus', 'Ptilotus'), ('Pultenaea', 'Pultenaea'), ('Quercus', 'Quercus'), ('Ranunculus', 'Ranunculus'), ('Rhododendron', 'Rhododendron'), ('Ribes', 'Ribes'), ('Rosa', 'Rosa'), ('Rubus', 'Rubus'), ('Salix', 'Salix'), ('Salvia', 'Salvia'), ('Saurauia', 'Saurauia'), ('Schefflera', 'Schefflera'), ('Scleria', 'Scleria'), ('Sedum', 'Sedum'), ('Senecio', 'Senecio'), ('Shorea', 'Shorea'), ('Silene', 'Silene'), ('Sisyrinchium', 'Sisyrinchium'), ('Solanum', 'Solanum'), ('Sorbus', 'Sorbus'), ('Sphagnum', 'Sphagnum'), ('Sporobolus', 'Sporobolus'), ('Stelis', 'Stelis'), ('Stylidium', 'Stylidium'), ('Symphyotrichum', 'Symphyotrichum'), ('Syzygium', 'Syzygium'), ('Taeniophyllum', 'Taeniophyllum'), ('Terminalia', 'Terminalia'), ('Teucrium', 'Teucrium'), ('Thelymitra', 'Thelymitra'), ('Tillandsia', 'Tillandsia'), ('Trisetum', 'Trisetum'), ('Utricularia', 'Utricularia'), ('Uvaria', 'Uvaria'), ('Vanilla', 'Vanilla'), ('Verbascum', 'Verbascum'), ('Vernonia', 'Vernonia'), ('Verticordia', 'Verticordia'), ('Viola', 'Viola'), ('Wahlenbergia', 'Wahlenbergia')], max_length=28, null=True)),
                ('name', models.TextField()),
                ('best_temperature', models.FloatField()),
                ('temperature_margin', models.FloatField()),
                ('best_air_humidity', models.FloatField()),
                ('air_humidity_margin', models.FloatField()),
                ('best_soil_moisture', models.FloatField()),
                ('soil_moisture_margin', models.FloatField()),
                ('best_light', models.FloatField()),
                ('light_margin', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('air_temperature', models.FloatField()),
                ('air_humidity', models.FloatField()),
                ('UV_index', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plant')),
            ],
        ),
    ]
