# Generated by Django 3.2.9 on 2021-11-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_plant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='air_humidity_margin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='best_air_humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='best_light',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='best_soil_moisture',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='best_temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='light_margin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil_moisture_margin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='temperature_margin',
            field=models.FloatField(null=True),
        ),
    ]
