# Generated by Django 3.2.9 on 2021-11-10 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211110_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='UV_index',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='air_humidity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='air_temperature',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-50.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='soil_moisture',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
